<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Medication;

class MedicationSeeder extends Seeder
{
    public function run(): void
    {
        $medications = [
            [
                'name' => 'Acetaminofén supositorios',
                'generic_name' => 'acetaminofén supositorios',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Acetaminofén jarabe',
                'generic_name' => 'acetaminofén jarabe',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Acetaminofén 500 mg tabletas',
                'generic_name' => 'acetaminofén 500 mg tabletas',
                'presentation' => 'Tabletas',
                'concentration' => '500 mg',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Adrenalina ampolla',
                'generic_name' => 'adrenalina ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Atropina ampolla',
                'generic_name' => 'atropina ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Aminofilina ampolla',
                'generic_name' => 'aminofilina ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Aspirina 81 mg tabletas',
                'generic_name' => 'aspirina 81 mg tabletas',
                'presentation' => 'Tabletas',
                'concentration' => '81 mg',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Alcohol frasco',
                'generic_name' => 'alcohol frasco',
                'presentation' => 'Frasco',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Algodón paquete',
                'generic_name' => 'algodón paquete',
                'presentation' => 'Paquete',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Agua destilada 5 ml',
                'generic_name' => 'agua destilada 5 ml',
                'presentation' => 'G',
                'concentration' => '5 ml',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Agua destilada 10 ml',
                'generic_name' => 'agua destilada 10 ml',
                'presentation' => 'G',
                'concentration' => '10 ml',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Agua oxigenada frasco',
                'generic_name' => 'agua oxigenada frasco',
                'presentation' => 'Frasco',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Antiácido suspensión',
                'generic_name' => 'antiácido suspensión',
                'presentation' => 'Suspensión',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Ácido ascórbico ampolla, vitamina C',
                'generic_name' => 'ácido ascórbico ampolla, vitamina c',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Agujas mariposas',
                'generic_name' => 'agujas mariposas',
                'presentation' => 'G',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Amikacina 500 mg',
                'generic_name' => 'amikacina 500 mg',
                'presentation' => 'G',
                'concentration' => '500 mg',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Bisturís No. 21 o No. 20',
                'generic_name' => 'bisturís no. 21 o no. 20',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Betadine',
                'generic_name' => 'betadine',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Bajante de suero',
                'generic_name' => 'bajante de suero',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Batas desechables',
                'generic_name' => 'batas desechables',
                'presentation' => 'Desechables',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Baja lengua',
                'generic_name' => 'baja lengua',
                'presentation' => 'G',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Bicarbonato de Sodio',
                'generic_name' => 'bicarbonato de sodio',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Bromuro de Ipratropio (nebulizar)',
                'generic_name' => 'bromuro de ipratropio (nebulizar)',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Vendaje elástico',
                'generic_name' => 'vendaje elástico',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Colector de orina adultos',
                'generic_name' => 'colector de orina adultos',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Colector de orina niños',
                'generic_name' => 'colector de orina niños',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Ciprofloxacina ampolla',
                'generic_name' => 'ciprofloxacina ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Cryopina ampolla',
                'generic_name' => 'cryopina ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Captopril 25 mg tabletas',
                'generic_name' => 'captopril 25 mg tabletas',
                'presentation' => 'Tabletas',
                'concentration' => '25 mg',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Captopril 50 mg tabletas',
                'generic_name' => 'captopril 50 mg tabletas',
                'presentation' => 'Tabletas',
                'concentration' => '50 mg',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Catéter 18',
                'generic_name' => 'catéter 18',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Catéter 20',
                'generic_name' => 'catéter 20',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Catéter 22',
                'generic_name' => 'catéter 22',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Catéter 24',
                'generic_name' => 'catéter 24',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Complejo B ampolla',
                'generic_name' => 'complejo b ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Clopidogrel 75 mg tabletas',
                'generic_name' => 'clopidogrel 75 mg tabletas',
                'presentation' => 'Tabletas',
                'concentration' => '75 mg',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Cánula de oxígeno',
                'generic_name' => 'cánula de oxígeno',
                'presentation' => 'G',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Dipirona ampolla',
                'generic_name' => 'dipirona ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Dexametasona ampolla',
                'generic_name' => 'dexametasona ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Dimenhidrinato ampolla',
                'generic_name' => 'dimenhidrinato ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Diclofenac ampolla',
                'generic_name' => 'diclofenac ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Dextrosa al 50% ampolla',
                'generic_name' => 'dextrosa al 50% ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '50%',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Diazepam ampolla',
                'generic_name' => 'diazepam ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Digoxina ampolla',
                'generic_name' => 'digoxina ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Difenhidramina ampolla',
                'generic_name' => 'difenhidramina ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Furosemida 40 mg tabletas',
                'generic_name' => 'furosemida 40 mg tabletas',
                'presentation' => 'Tabletas',
                'concentration' => '40 mg',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Furosemida ampolla',
                'generic_name' => 'furosemida ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Fitomenadiona ampolla (vitamina K)',
                'generic_name' => 'fitomenadiona ampolla (vitamina k)',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Fenitoína 250 mg',
                'generic_name' => 'fenitoína 250 mg',
                'presentation' => 'G',
                'concentration' => '250 mg',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Gel lubricante',
                'generic_name' => 'gel lubricante',
                'presentation' => 'G',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Gluconato de calcio 9.5% ampolla',
                'generic_name' => 'gluconato de calcio 9.5% ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '9.5%',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Gasa estéril',
                'generic_name' => 'gasa estéril',
                'presentation' => 'G',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Gorros quirúrgicos',
                'generic_name' => 'gorros quirúrgicos',
                'presentation' => 'G',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Guantes sueltos',
                'generic_name' => 'guantes sueltos',
                'presentation' => 'Sueltos',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Guantes estériles',
                'generic_name' => 'guantes estériles',
                'presentation' => 'Estériles',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Hilo nylon 3-0',
                'generic_name' => 'hilo nylon 3-0',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Hilo nylon 4-0',
                'generic_name' => 'hilo nylon 4-0',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Hilo nylon 5-0',
                'generic_name' => 'hilo nylon 5-0',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Hilo nylon 2-0',
                'generic_name' => 'hilo nylon 2-0',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Hilo vicryl 2-0, 3-0, 4-0',
                'generic_name' => 'hilo vicryl 2-0, 3-0, 4-0',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Hyaminol frasco',
                'generic_name' => 'hyaminol frasco',
                'presentation' => 'Frasco',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Hidrocortisona ampolla',
                'generic_name' => 'hidrocortisona ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Hidralazina 20 mg 1 ml',
                'generic_name' => 'hidralazina 20 mg 1 ml',
                'presentation' => 'G',
                'concentration' => '20 mg',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Heparina / Enoxaparina',
                'generic_name' => 'heparina / enoxaparina',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Ipratropio bromuro',
                'generic_name' => 'ipratropio bromuro',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Jeringa 1 ml',
                'generic_name' => 'jeringa 1 ml',
                'presentation' => 'G',
                'concentration' => '1 ml',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Jeringa 3 ml',
                'generic_name' => 'jeringa 3 ml',
                'presentation' => 'G',
                'concentration' => '3 ml',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Jeringa 5 ml',
                'generic_name' => 'jeringa 5 ml',
                'presentation' => 'G',
                'concentration' => '5 ml',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Jeringa 10 ml',
                'generic_name' => 'jeringa 10 ml',
                'presentation' => 'G',
                'concentration' => '10 ml',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Jabón quirúrgico',
                'generic_name' => 'jabón quirúrgico',
                'presentation' => 'G',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Ketorolaco ampolla',
                'generic_name' => 'ketorolaco ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Lidocaína sin epinefrina',
                'generic_name' => 'lidocaína sin epinefrina',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Metamizol 1 g ampolla',
                'generic_name' => 'metamizol 1 g ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '1 g',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Metronidazol ampolla',
                'generic_name' => 'metronidazol ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Metoclopramida ampolla',
                'generic_name' => 'metoclopramida ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Mascarillas quirúrgicas desechables',
                'generic_name' => 'mascarillas quirúrgicas desechables',
                'presentation' => 'G',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Mascarilla nebulizador niños',
                'generic_name' => 'mascarilla nebulizador niños',
                'presentation' => 'Nebulizador',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Mascarilla nebulizador adultos',
                'generic_name' => 'mascarilla nebulizador adultos',
                'presentation' => 'Nebulizador',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Nasales desechables',
                'generic_name' => 'nasales desechables',
                'presentation' => 'Desechables',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'N-butil ampolla',
                'generic_name' => 'n-butil ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Oxitocina 10 IU ampolla',
                'generic_name' => 'oxitocina 10 iu ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '10 IU',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Omeprazol 40 mg ampolla',
                'generic_name' => 'omeprazol 40 mg ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '40 mg',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Papel para camillas (rollo)',
                'generic_name' => 'papel para camillas (rollo)',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Ranitidina ampolla',
                'generic_name' => 'ranitidina ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Salbutamol gotas (nebulizar)',
                'generic_name' => 'salbutamol gotas (nebulizar)',
                'presentation' => 'G',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Sertal compuesto ampolla',
                'generic_name' => 'sertal compuesto ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Sonda vesical No. 14',
                'generic_name' => 'sonda vesical no. 14',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Sonda vesical No. 16',
                'generic_name' => 'sonda vesical no. 16',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Sonda vesical No. 18',
                'generic_name' => 'sonda vesical no. 18',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Solución salina 0.9% 1000 ml',
                'generic_name' => 'solución salina 0.9% 1000 ml',
                'presentation' => 'Ml',
                'concentration' => '0.9%',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Solución salina 0.9% 500 ml',
                'generic_name' => 'solución salina 0.9% 500 ml',
                'presentation' => 'Ml',
                'concentration' => '0.9%',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Solución salina 0.9% 100 ml',
                'generic_name' => 'solución salina 0.9% 100 ml',
                'presentation' => 'Ml',
                'concentration' => '0.9%',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Solución mixta al 33%',
                'generic_name' => 'solución mixta al 33%',
                'presentation' => 'Otro',
                'concentration' => '33%',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Solución Ringer',
                'generic_name' => 'solución ringer',
                'presentation' => 'G',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Solución mixta al 0.9%',
                'generic_name' => 'solución mixta al 0.9%',
                'presentation' => 'Otro',
                'concentration' => '0.9%',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Solución dextrosa 5%',
                'generic_name' => 'solución dextrosa 5%',
                'presentation' => 'Otro',
                'concentration' => '5%',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Sulfato de magnesio ampolla',
                'generic_name' => 'sulfato de magnesio ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Tramadol 50 mg ampolla',
                'generic_name' => 'tramadol 50 mg ampolla',
                'presentation' => 'Ampolla',
                'concentration' => '50 mg',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Termómetro',
                'generic_name' => 'termómetro',
                'presentation' => 'Otro',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ],
            [
                'name' => 'Termómetro digital',
                'generic_name' => 'termómetro digital',
                'presentation' => 'G',
                'concentration' => '',
                'manufacturer' => 'Desconocido',
                'lot_number' => null,
                'expiration_date' => date('Y-m-d', strtotime('+1 year')),
                'quantity' => 100,
                'unit_price' => 0,
                'entry_type' => 'purchase',
                'notes' => 'Registro inicial',
                'status' => true,
            ]
        ];

        foreach ($medications as $medication) {
            Medication::create($medication);
        }
    }
}
